# Pipeline Template - Story 2.1
# Generated by @ananda.matos

from sklearn.linear_model import LogisticRegression
import joblib

def build_pipeline():
    # Parâmetros definidos na Task T2.1.2
    model = LogisticRegression(class_weight='balanced', max_iter=1000)
    print("✅ Modelo instanciado com foco em RECALL")
    return model

if __name__ == "__main__":
    model = build_pipeline()
    # Placeholder para o fit/save
