openapi: 3.0.0
info:
  title: FlightOnTime ML API
  version: 1.0.0
paths:
  /predict:
    post:
      summary: Predição de atraso de voo
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  previsao: {type: integer, example: 1}
                  probabilidade: {type: float, example: 0.88}
                  custo_evitado: {type: float, example: 450.00}
  /health:
    get:
      summary: Health check para monitoramento
      responses:
        '200':
          description: API is alive
