openapi: 3.0.0
info:
  title: FlightOnTime API
  version: 1.0.0
paths:
  /predict:
    post:
      summary: Retorna predição de atraso.
      timeout: 2.0s
  /health:
    get:
      summary: Monitoramento do status.
